# .github/release.yml

changelog:
  categories:
    - title: Profile 🛠
      labels:
        - feature-profile
    - title: Jobs 🎉
      labels:
        - feature-jobs
    - title: Performance 🏋🏼‍
      labels:
        - feature-performance 
    - title: Other Changes
      labels:
        - "*"
