# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - a
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - b
    - title: Other Changes
      labels:
        - "*"
