# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - feature-productivity
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - feature-profile
    - title: Other Changes
      labels:
        - "*"
